name: 'ESDP2020_bot'
description: 'https://github.com/ESPD2020-2/ESDP2020'
author: 'Aman'
inputs:
  chat:
    description: '708896429'
    required: true
  token:
    description: '1246038903:AAFGceQpZj70OdlIOVXQEesPKvEklUw5bzQ'
    required: true
  status:
    description: 'Job status'
    required: true
  iu_title:
    description: 'Issue Title'
    default: ${{ github.event.issue.title }}
  iu_num:
    description: 'Issue Number'
    default: ${{ github.event.issue.number }}
  iu_actor:
    description: 'Issue Triggerer'
    default: ${{ github.event.issue.user.login }}
  iu_com:
    description: 'Issue Comment'
    default: ${{github.event.comment.body}}
  pr_state:
    description: 'State of the PR'
    default: ${{ github.event.action }}
  pr_num:
    description: 'PR Number'
    default: ${{ github.event.number }}
  pr_title:
    description: 'Title of the PR'
    default: ${{ github.event.pull_request.title }}
  pr_body:
    description: 'Body/Contents of the PR'
    default: ${{ github.event.pull_request.body }}
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'repeat'
  color: 'green'